<a href="https://colab.research.google.com/github/Miokasa/MLC/blob/master/Week4_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

pd.__version__

'2.2.2'

Datastructures:
* Series
* Dataframes

In [ ]:
data = [1,2,3,4,5]

series = pd.Series(data)

series

#df.info()
#df.describe()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
import numpy as np

data = np.array([10,20,30,40])
print(data)

series_np = pd.Series(data)

print(series_np)


dictionary = {'a':1, 'b':2}

dict_series = pd.Series(dictionary)
print(dict_series)

[10 20 30 40]
0    10
1    20
2    30
3    40
dtype: int64
a    1
b    2
dtype: int64

In [ ]:
print(series_np[2])


dict_series['b']


print(series_np[1:3])

30
1    20
2    30
dtype: int64

In [ ]:
series_np * 10

0    100
1    200
2    300
3    400
dtype: int64

In [ ]:
data = [1,2,np.nan, 4, 5]

series = pd.Series(data)

series

print(series.isnull())
# print(series.fillna(0))

print(series.dropna())

#series.isnull()
#series.fillna(0)
#series.dropna()

0    False
1    False
2     True
3    False
4    False
dtype: bool
0    1.0
1    2.0
3    4.0
4    5.0
dtype: float64

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [23,24,25],
    'City': ['Urbana', 'Chicago', 'LA']
}

df = pd.DataFrame(data)

df

      Name  Age     City
0    Alice   23   Urbana
1      Bob   24  Chicago
2  Charlie   25       LA

In [ ]:
# data = [
#     {'Name':'A', 'Age':25, 'City': 'NY'},
#     {'Name':'B', 'Age':22, 'City': 'LA'},
#     {'Name':'C', 'Age':21, 'City': 'Houston'},
#     {'Name':'D', 'Age':20, 'City': 'Austin'}
# ]

data = [
    ['A',24,'NY'],
    ['B',22, 'LA'],
    ['C',21, 'Houston']
]

df_list_dict = pd.DataFrame(data)
df_list_dict

   0   1        2
0  A  24       NY
1  B  22       LA
2  C  21  Houston

In [ ]:
# .iloc()
# .loc()

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [23,24,25],
    'City': ['Urbana', 'Chicago', 'LA']
}

df = pd.DataFrame(data)


print(df)
print("-------------------------------------")
print(df[['Name','Age']])
#df[['Name','Age']]
print("-------------------------------------")
print(df.iloc[0:2])
print("-------------------------------------")
print(df.loc[0:3])
print("-------------------------------------")

print(df[df['Age']>23])
print("-------------------------------------")
print(df.loc[0,'Age'] == 32)
print("-------------------------------------")

      Name  Age     City
0    Alice   23   Urbana
1      Bob   24  Chicago
2  Charlie   25       LA
-------------------------------------
      Name  Age
0    Alice   23
1      Bob   24
2  Charlie   25
-------------------------------------
    Name  Age     City
0  Alice   23   Urbana
1    Bob   24  Chicago
-------------------------------------
      Name  Age     City
0    Alice   23   Urbana
1      Bob   24  Chicago
2  Charlie   25       LA
-------------------------------------
      Name  Age     City
1      Bob   24  Chicago
2  Charlie   25       LA
-------------------------------------
False
-------------------------------------

In [ ]:
import numpy as np

df_with_nan = df.copy()

df_with_nan.loc[2,'Age'] = np.nan

df_with_nan

# ss=df.copy()
# ss.iloc[1,'Name']=np.nan
# ss

      Name   Age     City
0    Alice  32.0   Urbana
1      Bob  24.0  Chicago
2  Charlie   NaN       LA

In [ ]:
df_with_nan.isnull()

# filled_df = df_with_nan.fillna(0)
# filled_df

dropped_df = df_with_nan.dropna()
dropped_df

    Name   Age     City
0  Alice  32.0   Urbana
1    Bob  24.0  Chicago

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [23,24,25],
    'City': ['Urbana', 'Chicago', 'LA']
}

df = pd.DataFrame(data)

df['Salary'] = [700,800,1000]

print(df)

#df.drop(columns=['Salary'])
#df.drop(columns=['Salary])
#new=df.rename(columns={'Name':'Full name','Age':'Sage'})
#new=df.rename(columns={'A':'b','C':'D'})

df_dropped_column = df.drop(columns=['Salary'])

rename_df = df.rename(columns= {'Name': 'Full name', 'Age': 'Years'})

print(rename_df)

      Name  Age     City  Salary
0    Alice   23   Urbana     700
1      Bob   24  Chicago     800
2  Charlie   25       LA    1000
  Full name  Years     City  Salary
0     Alice     23   Urbana     700
1       Bob     24  Chicago     800
2   Charlie     25       LA    1000

In [ ]:
data = {'Cars': ['A', 'B', 'A','C', 'D', 'E', 'A', 'B'],
        'Prices': [100, 200, 100, 300, 400, 500, 100, 200]}

df = pd.DataFrame(data)
print(df)
grouped_df = df.groupby('Cars')['Prices'].sum()
#grouped=df.groupby('Cars')['Price].sum()
grouped_df

  Cars  Prices
0    A     100
1    B     200
2    A     100
3    C     300
4    D     400
5    E     500
6    A     100
7    B     200

Cars
A    300
B    400
C    300
D    400
E    500
Name: Prices, dtype: int64

In [ ]:
data1 = {
    'Name': ['a','b','c'],
    'Class': [1,2,3]
}

df1 = pd.DataFrame(data1)
print(df1)

data2 = {
    'Age': [10,11,12],
    'City': ['Chicago', 'Ohio', 'Houston'],
    'Name': ['a','b','c']
}

df2 = pd.DataFrame(data2)

print(df2)

merged_df = pd.merge(df1, df2, on= 'Name')
# merged=pd.merge(df1,df2,on='Name')
print(merged_df)

  Name  Class
0    a      1
1    b      2
2    c      3
   Age     City Name
0   10  Chicago    a
1   11     Ohio    b
2   12  Houston    c
  Name  Class  Age     City
0    a      1   10  Chicago
1    b      2   11     Ohio
2    c      3   12  Houston

In [ ]:
df_concat = pd.concat([df1,df2], axis=1)
df_concat
#df=pd.concat([df1,df2],axis=1)

  Name  Class  Age     City Name
0    a      1   10  Chicago    a
1    b      2   11     Ohio    b
2    c      3   12  Houston    c

In [ ]:
data = {
    'Department': ['HR', 'Engineering', 'Marketing', 'Finance', 'Sales', 'HR', 'Engineering', 'Marketing', 'Finance', 'Sales'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'Salary': [70000, 80000, 60000, 90000, 75000, 72000, 85000, 62000, 91000, 76000],
    'Years': [5, 6, 3, 8, 7, 4, 5, 2, 9, 6]
}

df = pd.DataFrame(data)
print(df)

grouped = df.groupby('Department')['Salary'].mean()

print(grouped)


grouped_multi = df.groupby(['Department', 'Years'])['Salary']
#grouped_multi=df.groupby(['A','B'])['Salary']
grouped_multi.mean()

    Department Employee  Salary  Years
0           HR    Alice   70000      5
1  Engineering      Bob   80000      6
2    Marketing  Charlie   60000      3
3      Finance    David   90000      8
4        Sales      Eve   75000      7
5           HR    Frank   72000      4
6  Engineering    Grace   85000      5
7    Marketing   Hannah   62000      2
8      Finance      Ivy   91000      9
9        Sales     Jack   76000      6
Department
Engineering    82500.0
Finance        90500.0
HR             71000.0
Marketing      61000.0
Sales          75500.0
Name: Salary, dtype: float64

Department   Years
Engineering  5        85000.0
             6        80000.0
Finance      8        90000.0
             9        91000.0
HR           4        72000.0
             5        70000.0
Marketing    2        62000.0
             3        60000.0
Sales        6        76000.0
             7        75000.0
Name: Salary, dtype: float64

In [ ]:
agg_data = df.groupby('Department').agg({
    'Salary': ['mean', 'sum'],
    'Years': ['mean', 'max']
})
# agg_data=df.groupby('Department').agg({'Salary':['mean','max'],'Year':['mean','max']})
agg_data

              Salary         Years
                mean     sum  mean max
Department
Engineering  82500.0  165000   5.5   6
Finance      90500.0  181000   8.5   9
HR           71000.0  142000   4.5   5
Marketing    61000.0  122000   2.5   3
Sales        75500.0  151000   6.5   7

In [ ]:
df['Salary_mean'] = df.groupby('Department')['Salary'].transform('mean')

df

    Department Employee  Salary  Years  Salary_mean
0           HR    Alice   70000      5      71000.0
1  Engineering      Bob   80000      6      82500.0
2    Marketing  Charlie   60000      3      61000.0
3      Finance    David   90000      8      90500.0
4        Sales      Eve   75000      7      75500.0
5           HR    Frank   72000      4      71000.0
6  Engineering    Grace   85000      5      82500.0
7    Marketing   Hannah   62000      2      61000.0
8      Finance      Ivy   91000      9      90500.0
9        Sales     Jack   76000      6      75500.0

In [ ]:
filtered = df.groupby('Department').filter(lambda x: x['Salary'].mean() > 75000)

filtered

    Department Employee  Salary  Years  Salary_mean
1  Engineering      Bob   80000      6      82500.0
3      Finance    David   90000      8      90500.0
4        Sales      Eve   75000      7      75500.0
6  Engineering    Grace   85000      5      82500.0
8      Finance      Ivy   91000      9      90500.0
9        Sales     Jack   76000      6      75500.0

In [ ]:
# index, columns, values, aggfunc

pivot = df.pivot_table(values = 'Salary', index = 'Department', columns = 'Years', aggfunc = ['mean','sum'], fill_value=0)

pivot

                mean                                                        \
Years              2        3        4        5        6        7        8
Department
Engineering      0.0      0.0      0.0  85000.0  80000.0      0.0      0.0
Finance          0.0      0.0      0.0      0.0      0.0      0.0  90000.0
HR               0.0      0.0  72000.0  70000.0      0.0      0.0      0.0
Marketing    62000.0  60000.0      0.0      0.0      0.0      0.0      0.0
Sales            0.0      0.0      0.0      0.0  76000.0  75000.0      0.0

                        sum
Years              9      2      3      4      5      6      7      8      9
Department
Engineering      0.0      0      0      0  85000  80000      0      0      0
Finance      91000.0      0      0      0      0      0      0  90000  91000
HR               0.0      0      0  72000  70000      0      0      0      0
Marketing        0.0  62000  60000      0      0      0      0      0      0
Sales            0.0      0      0      0      0  76000  75000      0      0

In [ ]:
df_csv = pd.read_csv('/content/sample_data/mnist_test.csv')

df_csv

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.to_csv('output.csv', index = False)

In [ ]:
df.to_excel('output.xlsx', index = False)

df.to_json('filename.json')

In [ ]:
import sqlite3

conn = sqlite3.connect('data.db')

df_sql = pd.read_sql_query('SELECT * FROM table_name', conn)

df_sql

df.to_sql('output_table', conn, if_exists='replace', index = False)

conn.close()

DatabaseError: Execution failed on sql 'SELECT * FROM table_name': no such table: table_name